### ISSUE TITLE
README instructions are misleading

### ISSUE THREAD

**Issue by m0rganic** [smarterclayton/cartridge-reflector#1]
`rhc create-app foo http://cartreflector-claytondev.rhcloud.com/reflect?github=smarterclayton/openshift-go-cart` 

results in the following error

```
Creating application 'foo' ... Invalid cartridge, error downloading from url 'http://cartreflector-claytondev.rhcloud.com/reflect?github=smarterclayton/openshift-go-cart'
```

Alternatively I found the [cartridge development kit](https://github.com/smarterclayton/openshift-cdk-cart/) is working. If this is no longer useful I suggest you take it down or label it as deprecated (assuming it's associated with cartridge v1.)

**Comment by smarterclayton** [comment]
This is fixed now (a while back actually) - just forgot to close this.  Thanks
